version: "3.10"
services:
  web:
    build: .
    command: >
      sh -c "python src/manage.py migrate &&
             python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    restart: "always"
    env_file:
      - ./.env